Parameters:
  SourceBucketName:
    Type: String
    Description: The name of the S3 bucket containing the source code.
  SourceObjectKey:
    Type: String
    Description: The key of the source code object in the S3 bucket.
  CodeBuildProjectName:
    Type: String
    Description: The name of the CodeBuild project to use for building the source code.
Resources:
    codepipelineservicerole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - codepipeline.amazonaws.com
                Action:
                  - sts:AssumeRole
          Policies:
            - PolicyName: codepipeline-service-role-policy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Action:
                      - s3:GetObject
                      - s3:GetObjectVersion
                      - s3:GetBucketVersioning
                      - s3:PutObject
                    Resource: "*"
                  - Effect: Allow
                    Action:
                      - codebuild:BatchGetBuilds
                      - codebuild:StartBuild
                    Resource: "*"
    codepipelinetest:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        Name: codepipeline-test
        RoleArn: !GetAtt codepipelineservicerole.Arn
        Stages:
          - Name: Source
            Actions:
              - Name: SourceAction
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Provider: S3
                  Version: 1
                OutputArtifacts:
                  - Name: SourceOutput
                Configuration:
                  S3Bucket: !Ref SourceBucketName
                  S3ObjectKey: !Ref SourceObjectKey
          - Name: Build
            Actions:
              - Name: BuildAction
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Provider: CodeBuild
                  Version: 1
                InputArtifacts:
                  - Name: SourceOutput
                OutputArtifacts:
                  - Name: BuildOutput
                Configuration:
                  ProjectName: !Ref CodeBuildProjectName

Output:
  codepipelinearn:
    Description: The ARN of the created CodePipeline.
    Value: !GetAtt codepipelinetest.Arn