AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CodeBuildProjectName:
    Type: String
    Description: The name of the CodeBuild project to be used in the CodePipeline.
    Default: codebuild-bootstrap
  SourceBucketName:
    Type: String
    Description: The name of the S3 bucket containing the source code.
    Default: "resourcetemplatecfn"
  SourceObjectKey:
    Type: String
    Description: The key of the source code object in the S3 bucket.
    Default: .
  
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/bootstrapbucketnested/codepipeline.yaml
      Parameters:
        codeBuildProjectName: !Ref CodeBuildProjectName
        sourceBucketName: !Ref SourceBucketName
        sourceObjectKey: !Ref SourceObjectKey