# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: "Configure AWS Credentials Action for GitHub Actions"
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          # AWS Region, e.g. us-east-2
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::211107604526:role/GitHubOIDCRole
          role-session-name: githuboidcaction
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: "Sync S3 Bucket"
        run: |
            ls -ltra
            aws s3 sync ./ s3://bootstrapbucketnested --exclude ".git/*" --exclude ".github/*" --delete
      - name: "Deploy CloudFormation Stack"
        run: |
            stacklist=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --output text)
            echo "$stacklist" | jq -r '.[]' | grep -w "bootstrap-stack" || echo "bootstrap-stack not found"

            # aws cloudformation create-stack \
            #     --template-file main.yaml \
            #     --stack-name bootstrap-stack \
            #     --capabilities CAPABILITY_NAMED_IAM
      
                      
      
